#!/usr/bin/env python3
"""Create a safe, container-first Colofon starter project."""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import automation
import make_doc
import workspace_paths


class InitError(Exception):
    """The requested project cannot be created without overwriting data."""


REQUIRED_EXAMPLES = {
    "article": ("title", "Example field note"),
    "bug-report": ("title", "Example synchronization defect"),
    "kb-article": ("title", "Example account recovery"),
    "memo": ("re", "Example readiness review"),
    "minutes": ("meeting", "Example planning meeting"),
    "onepager": ("title", "Example service overview"),
    "release-notes": ("product", "Example Relay"),
    "report": ("title", "Example readiness report"),
    "runbook": ("title", "Example recovery runbook"),
}


def document_source(doctype, brand=None):
    key, value = REQUIRED_EXAMPLES[doctype]
    front = ["---", f"doctype: {doctype}", f"{key}: {value}"]
    if brand:
        front.append(f"brand: {brand}")
    front.extend(["---", ""])
    body = [
        "> Fictional, AI-generated placeholder created for example purposes. Replace this",
        "> content before publishing.",
        "",
        "# Overview {#overview}",
        "",
        "This starter document demonstrates Colofon's Markdown authoring path.",
        "",
        "> [!tip]",
        "> Run the linter before building the verified PDF.",
        "",
    ]
    return "\n".join(front + body)


def book_spec(brand=None):
    lines = [
        "title: Example Handbook",
        "subtitle: Fictional, AI-generated starter for example purposes",
    ]
    if brand:
        lines.append(f"brand: {brand}")
    lines.extend([
        "parts:",
        "  - title: Start",
        "    blurb: Replace this fictional starter material with your own content.",
        "    chapters:",
        "      - chapters/01-welcome.md",
        "",
    ])
    return "\n".join(lines)


def chapter_source():
    return """# Welcome {#welcome}

> [!note]
> This chapter is fictional and AI-generated for example purposes. Replace it before
> publishing.

Colofon books keep their structure in `book.yaml` and their content in Markdown.

## Next step {#next-step}

Edit this chapter, then lint and build the book using the commands in the project README.
"""


def brand_package(name):
    manifest = f"""[package]
name = "{name}"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Example Organization"]
license = "MIT"
description = "Fictional starter brand generated by Colofon for example purposes."
"""
    source = """// Fictional, AI-generated starter brand for example purposes.
#let theme = (
  accent: rgb("#315C8C"),
  accent2: rgb("#24476D"),
  tones: (
    note: rgb("#315C8C"),
    tip: rgb("#2F7D4A"),
    important: rgb("#24476D"),
    warning: rgb("#A86512"),
    caution: rgb("#A33A32"),
  ),
)

#let author = "Example Organization"
#let colophon = [Fictional starter brand. Replace before publishing.]
#let book-args = (theme: theme, author: author, colophon: colophon)
"""
    return manifest, source


def project_readme(doctype, include_document, include_book, brand=None):
    image = f"ghcr.io/jmurray2011/colofon:{automation.FACTORY_VERSION}"
    document = f"documents/example-{doctype}.md"
    lines = [
        "# Colofon starter project",
        "",
        "The included content and optional brand are fictional and AI-generated for example",
        "purposes. Replace them before publishing.",
        "",
        "The commands below use an immutable Colofon container with the complete toolchain.",
        "Run them from this directory.",
        "",
        "```sh",
    ]
    if include_document:
        lines.extend([
            f'docker run --rm --user "$(id -u):$(id -g)" -v "$PWD:/work" {image} lint {document}',
            f'docker run --rm --user "$(id -u):$(id -g)" -v "$PWD:/work" {image} doc {document} -o build/example-{doctype}.pdf',
        ])
    if include_book:
        lines.append(
            f'docker run --rm --user "$(id -u):$(id -g)" -v "$PWD:/work" {image} book book/book.yaml -o build/example-book.pdf'
        )
    lines.extend(["```", ""])
    if brand:
        lines.extend([
            f"The generated `{brand}` package is under `packages/local/{brand}/0.1.0/`.",
            "Edit that package once to change the palette and colophon across the project.",
            "",
        ])
    return "\n".join(lines)


def plan(kind="both", doctype="report", brand=None):
    if brand:
        workspace_paths.package_name(brand)
    include_document = kind in ("document", "both")
    include_book = kind in ("book", "both")
    files = {
        ".gitignore": "build/\n.factory-build/\n",
        "README.md": project_readme(doctype, include_document, include_book, brand),
    }
    if include_document:
        files[f"documents/example-{doctype}.md"] = document_source(doctype, brand)
    if include_book:
        files["book/book.yaml"] = book_spec(brand)
        files["book/chapters/01-welcome.md"] = chapter_source()
    if brand:
        manifest, source = brand_package(brand)
        base = f"packages/local/{brand}/0.1.0"
        files[f"{base}/typst.toml"] = manifest
        files[f"{base}/lib.typ"] = source
    return files


def initialize(target, files, dry_run=False):
    root = os.path.abspath(target)
    if os.path.lexists(root) and (os.path.islink(root) or not os.path.isdir(root)):
        raise InitError(f"target is not a regular directory: {root}")
    existing = [relative for relative in files if os.path.lexists(os.path.join(root, relative))]
    if existing:
        raise InitError("refusing to overwrite existing file(s): " + ", ".join(sorted(existing)))
    if not dry_run:
        os.makedirs(root, exist_ok=True)
        for relative, content in sorted(files.items()):
            destination = os.path.join(root, relative)
            os.makedirs(os.path.dirname(destination), exist_ok=True)
            with open(destination, "x", encoding="utf-8") as output:
                output.write(content)
    return root, sorted(files)


def main():
    parser = argparse.ArgumentParser(description="create a safe Colofon starter project")
    parser.add_argument("directory", nargs="?", default=".")
    parser.add_argument("--kind", choices=("document", "book", "both"), default="both")
    parser.add_argument("--doctype", choices=make_doc.DOCTYPES, default="report")
    parser.add_argument("--brand", help="optional lowercase package name for a starter brand")
    parser.add_argument("--dry-run", action="store_true", help="list files without writing")
    parser.add_argument("--json", action="store_true", help="emit a structured result")
    args = parser.parse_args()
    try:
        files = plan(args.kind, args.doctype, args.brand)
        target, created = initialize(args.directory, files, args.dry_run)
    except (InitError, workspace_paths.WorkspacePathError) as error:
        if args.json:
            automation.emit(automation.failure("project-init", error, args.directory))
            return 1
        print(f"colofon init: {error}", file=sys.stderr)
        return 1
    payload = {
        "api_version": automation.API_VERSION,
        "dry_run": args.dry_run,
        "files": created,
        "kind": "project-init",
        "ok": True,
        "target": target,
    }
    if args.json:
        automation.emit(payload)
    else:
        action = "would create" if args.dry_run else "created"
        print(f"Colofon starter {action} at {target}")
        for relative in created:
            print(f"  {relative}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
